

name: Build Sitri
on:
  push:
permissions:
  contents: write
  deployments: write
  packages: write


env:
  FORCE_COLOR: true

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.21.1"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go dependencies
        run: go get -v

      - name: Build 
        run: go build


      - name: Update executable
        run: |
          chmod +x sitri

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Sitri-linux
          path: sitri


  build-mac:
    runs-on: macos-latest

    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.21.1"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go dependencies
        run: go get -v

      - name: Build
        run: go build -o sitri-mac

      - name: Update executable
        run: |
          chmod +x sitri-mac

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Sitri-mac
          path: sitri-mac


  build-windows:
    runs-on: windows-latest

    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.21.1"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build
        run: go build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Sitri-windows
          path: |
            sitri.exe

  release:
    runs-on: ubuntu-latest
    needs: [ build-linux, build-mac, build-windows ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.1.1
        with:
            name: Sitri-windows
            path: dist
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.1.1
        with:
            name: Sitri-mac
            path: dist
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.1.1
        with:
            name: Sitri-linux
            path: dist
      - name: Upload as release       
        run: |
            gh release upload sitri --clobber dist/*
        env:
            GITHUB_TOKEN: ${{ secrets.ghToken }}
          
